### ISSUE TITLE
missing test file

### ISSUE THREAD

**Issue by themaddoctor** [libyal/libcfile#4]
Missing test executable: ./cfile-20170105_test_write.exe

Maybe it's built on windows? I have linux.

**Comment by joachimmetz** [comment]
The test file should be cfile_test_write.exe, this likely due to incorrect detection of the prefix. I'll have a look if time permits.

**Comment by joachimmetz** [comment]
This was addressed in https://github.com/libyal/libcfile/commit/83b4186d784dc5aad48adf0fe3e93ea268319cb0#diff-7c086ee8dd3d0aff451b84caf0c0ee26. I'll prep a new release.

**Comment by joachimmetz** [comment]
Try: https://github.com/libyal/libcfile/releases/tag/20180102

**Comment by themaddoctor** [comment]
New release passes tests. Closing.
